// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'board-main-content': string;
  'board-wrapper': string;
  'main-inner': string;
}
export const cssExports: CssExports;
export default cssExports;
