// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add-board': string;
  'board-menu': string;
  'board-menu-wrapper': string;
  'board-name': string;
  'board-name__wrapper': string;
  'board__delete': string;
  'button-wrapper': string;
  'input-form': string;
  'menu-body-wrapper': string;
  'menu-header': string;
}
export const cssExports: CssExports;
export default cssExports;
