// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkbox-label': string;
  'checkbox-wrapper': string;
  'checkbox__delete': string;
  'checklist-section__delete': string;
  'checklist-section__header': string;
  'checklist-section__title': string;
  'checklist__add': string;
  'checklist__add-item': string;
  'checklist__close': string;
  'checklist__header': string;
  'checklist__progress': string;
  'checklist__textarea-description': string;
  'checklist__title': string;
  'checklist__title-buttons': string;
  'checklist__wrapper': string;
  'custom-checkbox': string;
  'progress__bar': string;
  'progress__bar_current': string;
  'progress__percentage': string;
}
export const cssExports: CssExports;
export default cssExports;
