// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checklist-section__delete': string;
  'checklist-section__header': string;
  'checklist-section__title': string;
  'checklist__add': string;
  'checklist__close': string;
  'checklist__header': string;
  'checklist__textarea-description': string;
  'checklist__title': string;
  'checklist__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
