// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add-button': string;
  'add-list-btn_wrapper': string;
  'addBtn-container': string;
  'card-list_wrapper': string;
  'close-input': string;
  'form': string;
  'hidden': string;
  'input-new-card': string;
  'open-add-list': string;
  'plus': string;
  'span-placeholder': string;
  'span-text': string;
}
export const cssExports: CssExports;
export default cssExports;
