// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'header-buttons': string;
  'header-buttons_text': string;
  'header-title': string;
  'left-block': string;
}
export const cssExports: CssExports;
export default cssExports;
