// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button__boards': string;
  'button__profile': string;
  'header__img': string;
  'header__left_column': string;
  'header__right_column': string;
  'header__title': string;
  'header__wrapper': string;
  'logout-button': string;
  'trello__icon': string;
}
export const cssExports: CssExports;
export default cssExports;
