// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button__boards': string;
  'button__burger': string;
  'button__create': string;
  'button__home': string;
  'button__notifications': string;
  'button__profile': string;
  'button__search': string;
  'create__icon': string;
  'header__img': string;
  'header__left_column': string;
  'header__loading_logo': string;
  'header__right_column': string;
  'header__title': string;
  'header__wrapper': string;
  'home__icon': string;
  'menu__icon': string;
  'notification__icon': string;
  'search__icon': string;
  'trello__icon': string;
  'header': string;
  'header-buttons': string;
  'header-buttons_text': string;
  'header-title': string;
  'left-block': string;
}
export const cssExports: CssExports;
export default cssExports;
