// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add-card-block__add-card-btn': string;
  'add-card-block__buttons': string;
  'add-card-block__close-btn': string;
  'add-card-block__controls': string;
  'add-card-block__menu': string;
  'black-back': string;
  'card-content': string;
  'card-header': string;
  'card-list': string;
  'card-list__add-btn': string;
  'card-list__add-card-block': string;
  'card-list__body': string;
  'card-list__bottom': string;
  'card-list__header': string;
  'card-list__inner': string;
  'card-list__menu-btn': string;
  'card-list__settings-btn': string;
  'card-name': string;
  'close-input': string;
  'rotate': string;
  'rotating': string;
}
export const cssExports: CssExports;
export default cssExports;
