// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'auth-wrapper': string;
  'error-message': string;
  'input-text': string;
  'login-form': string;
  'login-header': string;
  'start-page': string;
  'text-or': string;
}
export const cssExports: CssExports;
export default cssExports;
