// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card-content': string;
  'card-header': string;
  'card-list': string;
  'card-list__add-btn': string;
  'card-list__body': string;
  'card-list__bottom': string;
  'card-list__header': string;
  'card-list__inner': string;
  'card-list__menu-btn': string;
  'card-name': string;
}
export const cssExports: CssExports;
export default cssExports;
