// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hidden': string;
  'overlay': string;
  'show': string;
}
export const cssExports: CssExports;
export default cssExports;
