// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'board-divider': string;
  'board-header': string;
  'board-members': string;
  'board-name': string;
}
export const cssExports: CssExports;
export default cssExports;
