// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add-list-btn-container': string;
  'close-menu': string;
  'header-name': string;
  'list-link': string;
  'menu-body': string;
  'menu-container': string;
  'menu-header': string;
  'select': string;
  'select-block': string;
  'select-label': string;
}
export const cssExports: CssExports;
export default cssExports;
