// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'footer_container': string;
  'github_info': string;
  'github_link': string;
  'github_links': string;
  'github_logo': string;
  'rs_image': string;
  'rs_link': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
