// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card__delete': string;
  'checklist-wrapper': string;
  'description__icon': string;
  'popup__body': string;
  'popup__buttons': string;
  'popup__card-name': string;
  'popup__close-button': string;
  'popup__description': string;
  'popup__description-header-wrapper': string;
  'popup__description-inner': string;
  'popup__description-wrapper': string;
  'popup__list-name': string;
  'popup__list-text': string;
  'popup__sidebar': string;
  'popup__sidebar-button': string;
  'popup__textarea-description': string;
  'popup__title': string;
  'popup__title-wrapper': string;
  'sidebar__popup': string;
  'sidebar__title': string;
  'sidebar__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
