// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'popup': string;
  'popup__inner': string;
}
export const cssExports: CssExports;
export default cssExports;
