// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add-button': string;
  'close-input': string;
}
export const cssExports: CssExports;
export default cssExports;
